// ===== SIGNATURE ELEMENT: THE MOOD BOARD =====
// Instead of a generic grid with percentage badges, matched artists are arranged
// around the reference look with hand-drawn-style connector lines, each annotated
// with the specific style attribute that earned the match — like a stylist
// marking up a board for a bride, not a search engine returning rows.

function moodNote(matchedOn, targetStyles) {
  if (matchedOn.length === 0) return "Closest available match — no exact style overlap, but a top-rated generalist";
  const lead = matchedOn[0];
  const notes = {
    "Soft Glam": "matched on the soft-glam, dewy finish",
    "Minimal/Dewy": "matched on minimal, skin-first finish",
    "Traditional": "matched on traditional bridal styling",
    "Heavy Kumkum": "matched on heavy kumkum, bold colour work",
    "Bold Bridal": "matched on bold, high-impact bridal looks",
    "HD Airbrush": "matched on HD airbrush technique",
    "Pastel": "matched on soft pastel tones",
    "Indo-Western": "matched on fusion, Indo-Western styling"
  };
  return notes[lead] || `matched on ${lead.toLowerCase()}`;
}

function renderMoodBoard(scored, targetStyles, queryLabel, refImage) {
  const refImg = refImage || scored[0].artist.portfolio[0];
  // positions for cards around the board — desktop layout, percentages of board container
  const positions = [
    { top: '2%',  left: '58%' },
    { top: '38%', left: '70%' },
    { top: '2%',  left: '4%'  },
    { top: '38%', left: '12%' }
  ];

  const cards = scored.map(({artist, score, matchedOn}, i) => `
    <div class="mb-card" id="mb-card-${i}" style="top:${positions[i].top}; left:${positions[i].left};" onclick="openArtist('${artist.id}')">
      <div class="mb-card-photo">
        <img src="${artist.photo}" alt="${artist.name}" loading="lazy">
        <div class="mb-score">${score}%</div>
      </div>
      <div class="mb-card-body">
        <div class="mb-card-name">${artist.name}</div>
        <div class="mb-card-area">${artist.area}</div>
        <div class="mb-card-note">${moodNote(matchedOn, targetStyles)}</div>
      </div>
    </div>
  `).join('');

  return `
  <section class="mood-board-section">
    <div class="section-pad" style="padding-top:56px; padding-bottom:24px;">
      <div style="display:flex; align-items:center; gap:10px; margin-bottom:6px; flex-wrap:wrap;">
        <span class="mono" style="font-size:11px; color:var(--rani); font-weight:700; text-transform:uppercase;">Matched on</span>
        ${targetStyles.map(s => `<span class="tag" style="background:var(--blush); opacity:1;">${s}</span>`).join('')}
      </div>
      <p style="font-size:13px; opacity:0.5;">for "${(queryLabel||'').length > 70 ? queryLabel.slice(0,70)+'…' : queryLabel}" — tap any artist to view their full profile</p>
    </div>

    <div class="mood-board" id="moodBoard">
      <svg class="mb-lines" id="mbLines" viewBox="0 0 1000 620" preserveAspectRatio="none"></svg>
      <div class="mb-center">
        <img src="${refImg}" alt="Reference look" id="mbRefImg">
        <div class="mb-center-label">Your reference</div>
      </div>
      ${cards}
    </div>

    <div class="section-pad" style="padding-top:8px;">
      <p style="font-size:12.5px; opacity:0.45; text-align:center;">Match scores are generated by comparing your description against each artist's tagged portfolio style — not a guarantee, a starting point for your search.</p>
    </div>
  </section>

  <style>
    .mood-board-section { background: var(--ivory-deep); }
    .mood-board {
      position: relative;
      max-width: 1100px; margin: 0 auto;
      height: 620px;
      padding: 0 40px;
    }
    .mb-lines { position: absolute; inset: 0; width: 100%; height: 100%; pointer-events: none; overflow: visible; }
    .mb-lines path {
      fill: none; stroke: var(--gold); stroke-width: 1.5; stroke-dasharray: 4 5;
      stroke-linecap: round; opacity: 0;
    }
    .mb-center {
      position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%);
      width: 220px; z-index: 5; text-align: center;
    }
    .mb-center img {
      width: 220px; height: 270px; object-fit: cover; border-radius: 8px;
      border: 6px solid white; box-shadow: var(--shadow-lg);
    }
    .mb-center-label {
      font-family: 'Fraunces', serif; font-style: italic; font-size: 14px;
      color: var(--rani); margin-top: 10px;
    }
    .mb-card {
      position: absolute; width: 220px;
      background: white; border-radius: 14px; overflow: hidden;
      box-shadow: var(--shadow); cursor: pointer;
      opacity: 0; transform: translateY(10px);
      transition: transform 0.25s, box-shadow 0.25s;
      z-index: 3;
    }
    .mb-card:hover { transform: translateY(-4px); box-shadow: var(--shadow-lg); }
    .mb-card.mb-in { animation: mbFadeIn 0.5s ease forwards; }
    @keyframes mbFadeIn { to { opacity: 1; transform: translateY(0); } }
    .mb-card-photo { position: relative; height: 130px; }
    .mb-card-photo img { width: 100%; height: 100%; object-fit: cover; display: block; }
    .mb-score {
      position: absolute; top: 8px; right: 8px;
      background: var(--rani); color: white; font-size: 11px; font-weight: 700;
      padding: 4px 9px; border-radius: 100px;
    }
    .mb-card-body { padding: 12px 14px 14px; }
    .mb-card-name { font-family: 'Fraunces', serif; font-size: 14.5px; font-weight: 600; margin-bottom: 2px; }
    .mb-card-area { font-size: 11px; opacity: 0.55; margin-bottom: 6px; }
    .mb-card-note { font-size: 11.5px; font-style: italic; color: var(--rani); opacity: 0.85; line-height: 1.4; }

    @media (max-width: 980px) {
      .mood-board { height: auto; padding: 24px 20px; }
      .mb-lines { display: none; }
      .mb-center { position: static; transform: none; margin: 0 auto 24px; }
      .mb-card { position: static; width: 100%; margin-bottom: 14px; opacity: 1; transform: none; }
    }
  </style>
  `;
}

function initMoodBoardLines() {
  const board = document.getElementById('moodBoard');
  const svg = document.getElementById('mbLines');
  if (!board || !svg) return;
  if (window.innerWidth <= 980) return; // mobile: stacked layout, no lines needed

  // stagger card entrance
  document.querySelectorAll('.mb-card').forEach((card, i) => {
    setTimeout(() => card.classList.add('mb-in'), 150 + i * 130);
  });

  setTimeout(() => {
    const boardRect = board.getBoundingClientRect();
    const center = document.querySelector('.mb-center');
    if (!center) return;
    const centerRect = center.getBoundingClientRect();
    const cx = (centerRect.left + centerRect.width/2 - boardRect.left) / boardRect.width * 1000;
    const cy = (centerRect.top + centerRect.height/2 - boardRect.top) / boardRect.height * 620;

    let pathsHtml = '';
    document.querySelectorAll('.mb-card').forEach((card, i) => {
      const r = card.getBoundingClientRect();
      const tx = (r.left + r.width/2 - boardRect.left) / boardRect.width * 1000;
      const ty = (r.top + r.height/2 - boardRect.top) / boardRect.height * 620;
      const mx = (cx + tx) / 2 + (i % 2 === 0 ? 30 : -30);
      const my = (cy + ty) / 2;
      pathsHtml += `<path id="mb-path-${i}" d="M ${cx} ${cy} Q ${mx} ${my} ${tx} ${ty}" />`;
    });
    svg.innerHTML = pathsHtml;

    document.querySelectorAll('.mb-lines path').forEach((path, i) => {
      const len = path.getTotalLength();
      path.style.strokeDasharray = `${len}`;
      path.style.strokeDashoffset = `${len}`;
      path.style.transition = 'none';
      setTimeout(() => {
        path.style.transition = 'stroke-dashoffset 0.8s ease, opacity 0.3s ease';
        path.style.opacity = '0.55';
        path.style.strokeDashoffset = '0';
      }, 200 + i * 130);
    });
  }, 100);
}

window.addEventListener('resize', () => {
  if (STATE.view === 'matcher' && document.getElementById('moodBoard')) {
    initMoodBoardLines();
  }
});
